#pragma once

#define MAKETEMP_VERSION "@PROJECT_VERSION@"
#define MAKETEMP_VERSION_MAJOR "@PROJECT_VERSION_MAJOR@"
#define MAKETEMP_VERSION_MINOR "@PROJECT_VERSION_MINOR@"
#define MAKETEMP_VERSION_PATCH "@PROJECT_VERSION_PATCH@"

#define MAKETEMP_EXE "@MAKETEMP_EXE@"
#define MAKETEMP_DEF_TEMPLATE "{}.tmp"